# Generated by Django 4.2.13 on 2024-07-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_vocational_tradecourse_item_senior_high'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='city',
            new_name='municipality',
        ),
    ]
