# Generated by Django 4.2.13 on 2024-07-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_city_item_municipality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='civil_status',
            new_name='marital_status',
        ),
    ]
